spring.application.name=Habit-Tracker
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/habitdb;AUTO_SERVER=TRUE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.open-in-view=false
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
app.security.username=${APP_SECURITY_USERNAME:admin}
app.security.email=${APP_SECURITY_EMAIL:admin@habittracker.local}
app.security.password=${APP_SECURITY_PASSWORD:admin123}
